meta_title: "Whiz : Livraison express "
meta_description: " Livraison de vos colis de point à point en 4h"
meta_image: "delivery.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@whiz_deliver" # indispensable pour les Twitter Cards
